import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Briefcase, Calendar, DollarSign, TrendingUp } from 'lucide-react';
import KPICard from '../components/KPICard';
import { useFirestoreCollection } from '../hooks/useFirestore';
const Projects = () => {
    const { data: projects } = useFirestoreCollection('projects');
    const { data: plants } = useFirestoreCollection('plants');
    const totalVolume = (projects ?? []).reduce((s, p) => s + p.totalVolume, 0);
    const avgPrice = projects && projects.length > 0
        ? projects.reduce((s, p) => s + p.salePricePerM3, 0) / projects.length
        : 0;
    const getPlantName = (plantId) => plants?.find(p => p.id === plantId)?.name ?? plantId;
    return (_jsxs(_Fragment, { children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8", children: [_jsx(KPICard, { title: "Total Proyectos", value: projects?.length ?? 0, icon: Briefcase }), _jsx(KPICard, { title: "Volumen Total", value: `${totalVolume.toLocaleString()} m³`, icon: Calendar }), _jsx(KPICard, { title: "Precio Prom. Venta", value: `$${avgPrice.toFixed(2)} /m³`, icon: DollarSign }), _jsx(KPICard, { title: "Duraci\u00F3n Promedio", value: projects && projects.length > 0 ? `${(projects.reduce((s, p) => s + p.durationMonths, 0) / projects.length).toFixed(0)} meses` : '-', icon: TrendingUp })] }), _jsxs("div", { className: "glass-card p-6 rounded-xl", children: [_jsxs("h3", { className: "font-bold text-lg mb-6 flex items-center gap-2", children: [_jsx(Briefcase, { className: "w-5 h-5" }), " Proyectos y Obras"] }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b border-border text-muted-foreground", children: [_jsx("th", { className: "text-left py-3 px-4", children: "Proyecto" }), _jsx("th", { className: "text-left py-3 px-4", children: "Planta" }), _jsx("th", { className: "text-right py-3 px-4", children: "Volumen (m\u00B3)" }), _jsx("th", { className: "text-right py-3 px-4", children: "Duraci\u00F3n (meses)" }), _jsx("th", { className: "text-right py-3 px-4", children: "Precio Venta /m\u00B3" }), _jsx("th", { className: "text-right py-3 px-4", children: "Tasa Descuento" }), _jsx("th", { className: "text-right py-3 px-4", children: "Ingreso Total" })] }) }), _jsx("tbody", { children: projects?.map((proj) => (_jsxs("tr", { className: "border-b border-border/50 hover:bg-primary/5 transition-colors", children: [_jsx("td", { className: "py-3 px-4 font-medium", children: proj.name }), _jsx("td", { className: "py-3 px-4 text-muted-foreground", children: getPlantName(proj.plantId) }), _jsx("td", { className: "py-3 px-4 text-right", children: proj.totalVolume.toLocaleString() }), _jsx("td", { className: "py-3 px-4 text-right", children: proj.durationMonths }), _jsxs("td", { className: "py-3 px-4 text-right", children: ["$", proj.salePricePerM3.toFixed(2)] }), _jsxs("td", { className: "py-3 px-4 text-right", children: [(proj.discountRate * 100).toFixed(1), "%"] }), _jsxs("td", { className: "py-3 px-4 text-right font-bold text-primary", children: ["$", (proj.totalVolume * proj.salePricePerM3).toLocaleString()] })] }, proj.id))) })] }) })] })] }));
};
export default Projects;
